"""Added main tables for car description

Revision ID: ca7785b1faf0
Revises: 8038fd887eee
Create Date: 2024-01-02 07:40:26.098725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7785b1faf0'
down_revision: Union[str, None] = '8038fd887eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, cache=10), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colors'))
    )
    op.create_table('engines',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, cache=10), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('volume', sa.REAL(), nullable=False),
    sa.Column('hps', sa.INTEGER(), nullable=False),
    sa.Column('consumption', sa.REAL(), nullable=False),
    sa.Column('acceleration', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engines'))
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, cache=10), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    op.create_table('transmission_types',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, cache=10), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transmission_types'))
    )
    op.create_table('model_colors',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, cache=10), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], name=op.f('fk_model_colors_color_id_colors'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_model_colors_model_id_models'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_colors'))
    )
    op.create_table('transmissions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, cache=10), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('speed', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['type'], ['transmission_types.id'], name=op.f('fk_transmissions_type_transmission_types'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transmissions'))
    )
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1, cache=10), nullable=False),
    sa.Column('model', sa.Integer(), nullable=False),
    sa.Column('engine', sa.Integer(), nullable=False),
    sa.Column('transmission', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['engine'], ['engines.id'], name=op.f('fk_equipments_engine_engines'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model'], ['models.id'], name=op.f('fk_equipments_model_models'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transmission'], ['transmissions.id'], name=op.f('fk_equipments_transmission_transmissions'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipments'))
    )
    op.create_table('cars',
    sa.Column('vin', sa.VARCHAR(length=17), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('equipment', sa.Integer(), nullable=False),
    sa.Column('model_color', sa.Integer(), nullable=False),
    sa.Column('extra_equipment', sa.TEXT(), nullable=True),
    sa.Column('gifts', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], name=op.f('fk_cars_dealer_id_dealers'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipment'], ['equipments.id'], name=op.f('fk_cars_equipment_equipments'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_color'], ['model_colors.id'], name=op.f('fk_cars_model_color_model_colors'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('vin', name=op.f('pk_cars'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    op.drop_table('equipments')
    op.drop_table('transmissions')
    op.drop_table('model_colors')
    op.drop_table('transmission_types')
    op.drop_table('models')
    op.drop_table('engines')
    op.drop_table('colors')
    # ### end Alembic commands ###
